### ISSUE TITLE
Custom URL's

### ISSUE THREAD

**Issue by LDanforth** [Esri/storymap-crowdsource#1]
The only complaint that I receive from clients about this app is that nobody can share a link directly to their story.  I tried looking for the router info but it seems to be missing from this app. Huge bummer.

**Comment by ssylvia** [comment]
Thanks for the comment. We have that feature on our list for a future release.

**Comment by tannerjt** [comment]
I am running into the same issue.  I would like to share individual stories.  What would be the best way to open a particular story given a queryParamater (probably objectid of feature)?

**Comment by ssylvia** [comment]
That would probably take some work at this point. Some things that would need to happen:

1. You probably don't want to show the cover page and have the loader wait until the map is fully loaded.
2. You will need to manually query that feature. The app will only query features that are in the current map extent. Once you have the location, you can center the map on that point. 
3. Finally, set that point as the selected feature and hide the loading (and cover-page).

**Comment by tannerjt** [comment]
Thanks @LDanforth for bringing up the original issue and @ssylvia for providing some guidance.  I have this working in my own app - https://s3.amazonaws.com/compassionreports/index.html?report=1608 - notice the report parameter at the end.  @LDanforth, if you are interested, you can see how I am doing this for the following branch - https://github.com/tannerjt/compassiongames_storymap/tree/queryparams
