### ISSUE TITLE
StoryMap Crowdsource symbol 

### ISSUE THREAD

**Issue by holly1234** [Esri/storymap-crowdsource#12]
Hi, 
I am having a play with AGO assistant and was wondering if there any way to change the symbol on a crowdsource map? There is not an obvious place but I might be missing something! Currently it is a white circle with a blue outline which doesn't stand out very well on my grey basemap. 

If not available is AGO assistant, is this possible when if I download the code? 

Thanks in advanced!

**Comment by ssylvia** [comment]
It is not possible with AGO Assistant but is possible if you are will download the code and modify the app. You would need to set the options on the cluster layer itself. Here are the available options: https://github.com/Esri/cluster-layer-js#developer-notes. There are few different ways to do it (see options with symbols). You can change the options here: https://github.com/Esri/storymap-crowdsource/blob/master/src/app/components/map/CrowdsourceWebmapController.babel.js#L131.
