### ISSUE TITLE
Deploying StoryMap Crowdsource as a template in Portal for ArcGIS

### ISSUE THREAD

**Issue by kanins** [Esri/storymap-crowdsource#18]
We tried to deploy the application as a template in Portal for ArcGIS 10.6. However, the application does not function properly as the points and images could not be displayed properly. We also tried to deploy and register it as an item in Portal for ArcGIS.  May I know if there are ways to deploy the application to Portal or if it is not currently supported, may I know if there is a timeline for StoryMap Crowdsource to be generally available (GA) and be installed out-of-the-box with Portal?

**Comment by ssylvia** [comment]
The Story Map Crowdsource Beta app is not supported on Portal. It will also not receive any more feature updates and will not be made available to portal. For more information, see this FAQ: http://storymaps.arcgis.com/en/faq/#question60.
