### ISSUE TITLE
Can this app be modified while in Esri mature support?

### ISSUE THREAD

**Issue by UnderJollyRoger** [Esri/storymap-crowdsource#19]
Hi,

I forked this app and I'm about to begin learning how to change the source code so that I can ultimately alphabetize (by title) end-user contributions. Then I read the app is being moved into mature support and will no longer be supported. I currently have three crowdsource apps up, and I want to still make these changes. Is this possible?

**Comment by ssylvia** [comment]
This repo will no longer receive updates but will remain available. With your fork, you can also continue maintain and fix bugs as needed. All customization will live on your server.
