### ISSUE TITLE
Custom Feilds

### ISSUE THREAD

**Issue by SamDrummond** [Esri/storymap-crowdsource#2]
Is there a way to incorporate custom fields into the feature service powering the crowdsource story map?

I have a customer that wants to add some custom fields - so the solution has a similar user experience to the [Tree Survey App](https://crowdsource.storymaps.esri.com/stories/tree-survey)

**Comment by ssylvia** [comment]
You can read more about customizing the crowdsource form in this blog post: https://developerscorner.storymaps.arcgis.com/custom-forms-in-the-story-map-crowdsource-beta-79af2014c8da#.u1h7lpx4v

**Comment by SamDrummond** [comment]
Thanks @ssylvia - this is perfect.
