### ISSUE TITLE
Domains and Dropdown lists

### ISSUE THREAD

**Issue by SamDrummond** [Esri/storymap-crowdsource#3]
At what point on the story map crowdsource builder roadmap, is Esri looking to implement automatic drop-down list for fields set up with domains?

Based on https://github.com/Esri/storymap-crowdsource/issues/2, I know that it is possible to customise this myself - however before I look at this I need to know what Esri's plans are.

**Comment by ssylvia** [comment]
We don't have a planned date for this yet. We have shifted priorities to integrate crowdsourcing into some of our existing apps before we start expanding the feature set. It will probably be at least 6 months before you see editable form. There are two other apps (Crowdsource Reporter and Survey 123) that already let you customize the form without editing the code.
