### ISSUE TITLE
Enforce number data types

### ISSUE THREAD

**Issue by tannerjt** [Esri/storymap-crowdsource#7]
In regards to validations, what is the best way to validate an input field to be of type: number?  I have several fields that are of type 'esriFieldTypeDouble' that I need to validate upon form submit, or onBlur.

**Comment by tannerjt** [comment]
It would be preferable to be able to specify the field as type: 'number' in the crowdsource layer config.

**Comment by ssylvia** [comment]
Yep, that should be pretty easy to do.

- Change the field type to `number`: https://github.com/Esri/storymap-crowdsource/blob/master/src/app/builderOptions.babel.js#L30. If you have already created the story, you'll need to change this through the AGO assistant.
- Then add `field.type === 'number'` to this list
- If you want to add additional validation rules to make sure it is a number for browsers that may fall back to text input (not sure if you will encounter this), you can extend this to ruleset: https://github.com/Esri/storymap-crowdsource/blob/master/src/app/utils/validations/rules/BasicRules.babel.js
- You can also rely on the `min/max` validations if you only want to allow ranges. You can add a rule to the validations setting: https://github.com/Esri/storymap-crowdsource/blob/master/src/app/utils/validations/rules/BasicRules.babel.js. `{rule: 'max', 'max': 100}` or `{rule: 'min', 'min': 0}`

**Comment by tannerjt** [comment]
Thank you!  I'll try this out tonight.

**Comment by tannerjt** [comment]
Works great, thanks again.
