### ISSUE TITLE
Optional Picture Submission

### ISSUE THREAD

**Issue by AmrEldib** [Esri/storymap-crowdsource#9]
In the workflow of one client's setup, submitting a picture doesn't apply to every user. They would like to make picture submission optional.
Using [ArcGIS Online Assistant](https://ago-assistant.esri.com/), we found a `required` flag and set it to `false`. However, this only removed the asterisk next to the picture field.
The Submit button was still not available unless I open the Upload Picture file dialog and then click Cancel.
Now, the Submit button can be clicked even though it still has a _Not Allowed_ mouse cursor. Submission goes through and a point is created in the feature service but the application fails to handle that, and it's stuck with submission status.
We're looking to make submitting pictures optional via the application itself, and not have to use the ArcGIS Online Assistant.
Please let me know if you have any questions.

**Comment by ssylvia** [comment]
The beta version of the Crowdsource app is not set up to handle contributions without a photo. We have not yet created a layout that works well without photo or works well when a photo is only provided for some points. You will need to download the source code and modify it if you need this as a solution. You will not be able to use the hosted version.
